// AUTO-GENERATED by build/middleware-gen.js — do not edit by hand.
// Per-species OG/Twitter metadata for the bundled HTML response, so
// /d/<slug> URLs render with the correct social-share preview before
// any JavaScript runs.

export const config = {
  // Run on /d/:slug only. Everything else (/, /timeline, /map, /about,
  // static files) bypasses middleware and gets the default response.
  matcher: '/d/:slug',
};

const META = {
  "tyrannosaurus-rex": {
    "name": "Tyrannosaurus rex",
    "teaser": "The one everyone draws first."
  },
  "triceratops": {
    "name": "Triceratops",
    "teaser": "Three horns, one giant frill, no patience."
  },
  "stegosaurus": {
    "name": "Stegosaurus",
    "teaser": "Plates on top, spikes on the back."
  },
  "brachiosaurus": {
    "name": "Brachiosaurus",
    "teaser": "Built like a four-story crane."
  },
  "velociraptor": {
    "name": "Velociraptor",
    "teaser": "Turkey-sized, fully feathered, very fast."
  },
  "spinosaurus": {
    "name": "Spinosaurus",
    "teaser": "Sail on its back, paddle for a tail."
  },
  "ankylosaurus": {
    "name": "Ankylosaurus",
    "teaser": "Living tank with a club for a tail."
  },
  "parasaurolophus": {
    "name": "Parasaurolophus",
    "teaser": "A trombone with legs."
  },
  "therizinosaurus": {
    "name": "Therizinosaurus",
    "teaser": "Giant feathered claws, salad eater."
  },
  "microraptor": {
    "name": "Microraptor",
    "teaser": "Four wings. Iridescent black. The size of a crow."
  },
  "diplodocus": {
    "name": "Diplodocus",
    "teaser": "All neck and tail, very little middle."
  },
  "allosaurus": {
    "name": "Allosaurus",
    "teaser": "The Jurassic's main predator."
  },
  "iguanodon": {
    "name": "Iguanodon",
    "teaser": "A thumb spike for trouble."
  },
  "pachycephalosaurus": {
    "name": "Pachycephalosaurus",
    "teaser": "Skull like a bowling ball."
  },
  "carnotaurus": {
    "name": "Carnotaurus",
    "teaser": "Bull-horned, fast, and tiny-armed."
  },
  "plateosaurus": {
    "name": "Plateosaurus",
    "teaser": "An early giant, before the giants."
  },
  "coelophysis": {
    "name": "Coelophysis",
    "teaser": "Slim, fast, hollow-boned."
  },
  "eoraptor": {
    "name": "Eoraptor",
    "teaser": "One of the very first dinosaurs."
  },
  "deinonychus": {
    "name": "Deinonychus",
    "teaser": "The real raptor everyone is thinking of."
  },
  "ichthyovenator": {
    "name": "Ichthyovenator",
    "teaser": "A spinosaur with a split sail."
  }
};

const esc = (s) => String(s)
  .replace(/&/g, '&amp;')
  .replace(/"/g, '&quot;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;');

export default async function middleware(request) {
  const url = new URL(request.url);
  const m = url.pathname.match(/^\/d\/([^\/]+)/);
  if (!m) return;

  const slug = m[1];
  const data = META[slug];
  if (!data) return; // unknown slug — fall through to the SPA, default OG

  // Fetch the bundled index.html. The matcher means this fetch (to /)
  // doesn't re-trigger middleware, no infinite loop.
  const upstream = await fetch(new URL('/', url));
  if (!upstream.ok) return;

  let html = await upstream.text();

  const title = `${data.name} — Rex's Notes`;
  const desc = data.teaser;
  const ogUrl = url.origin + url.pathname;
  const ogImage = `${url.origin}/og/${slug}.png`;

  // Replace meta tags. Match the exact opening attribute so we only
  // touch the tags shell.html emits, not anything inside the bundle.
  const replacements = [
    [/<title>[\s\S]*?<\/title>/, `<title>${esc(title)}</title>`],
    [/<meta name="description" content="[^"]*">/, `<meta name="description" content="${esc(desc)}">`],
    [/<link rel="canonical" href="[^"]*">/, `<link rel="canonical" href="${ogUrl}">`],
    [/<meta property="og:title" content="[^"]*">/, `<meta property="og:title" content="${esc(title)}">`],
    [/<meta property="og:description" content="[^"]*">/, `<meta property="og:description" content="${esc(desc)}">`],
    [/<meta property="og:url" content="[^"]*">/, `<meta property="og:url" content="${ogUrl}">`],
    [/<meta property="og:image" content="[^"]*">/, `<meta property="og:image" content="${ogImage}">`],
    [/<meta property="og:image:alt" content="[^"]*">/, `<meta property="og:image:alt" content="${esc(data.name)} — illustration on cream paper.">`],
    [/<meta name="twitter:title" content="[^"]*">/, `<meta name="twitter:title" content="${esc(title)}">`],
    [/<meta name="twitter:description" content="[^"]*">/, `<meta name="twitter:description" content="${esc(desc)}">`],
    [/<meta name="twitter:image" content="[^"]*">/, `<meta name="twitter:image" content="${ogImage}">`],
  ];
  for (const [re, val] of replacements) html = html.replace(re, val);

  return new Response(html, {
    status: 200,
    headers: {
      'content-type': 'text/html; charset=utf-8',
      'cache-control': 'public, max-age=300, s-maxage=86400',
    },
  });
}
